### PR TITLE
Handle string inputs in perf_client

### PR DESCRIPTION
**Pull request by jobegrabber**
Currently perf_client can't handle input tensors with an unfixed `ByteSize`, i.e. input tensors with variable-size shapes and string input tensors.

This PR will allow perf_client to be used with models using string input tensors.
Empty strings with a specified length (default 128) are used as mock values.

This PR _does not_ yet implement reading of provided data from input files.
I see that there's ongoing development to refactor the perf_client (#505), so I'm unsure whether to implement this as well. It's a bit more complicated to read in string input data.

### CODE REVIEW

**Comment by GuanLuo** [comment]
The PR #505 is mostly breaking down the perf_client into multiple files for different classes, and it is merged into master now so you will have to rebase to master and convert your changes accordingly. I think the majority of your change will just be in `concurrency_manager.cc`

**Comment by jobegrabber** [comment]
Thanks, @GuanLuo !

**Comment by tanmayv25** [comment]
Hi @jobegrabber, 
I have started working on allowing string inputs in perf-client.

**Comment by jobegrabber** [comment]
@tanmayv25 Thanks for that! I've been pretty busy on other things right now, so I guess it makes sense to close this PR for now.

**Comment by jobegrabber** [comment]
@tanmayv25 Thanks for that! I've been pretty busy on other things right now, so I guess it makes sense to close this PR for now.

**Pull request closed without merging**
